### ISSUE TITLE
Work contract

### ISSUE THREAD

**Issue by Galidar** [DaiZiLing/Flux2ShorelineWaveHLSL#1]
Good morning, My name is Galidar and I am the creator of the Oceanology plugin at epic games, we would like to contact you to achieve some effects in our ocean, we are willing to hire you if there is the possibility
https://discord.gg/GBd8DcFsKf
Can we talk privately in my community please? 
Company@Galidar.online

**Comment by DaiZiLing** [comment]
> Good morning, My name is Galidar and I am the creator of the Oceanology plugin at epic games, we would like to contact you to achieve some effects in our ocean, we are willing to hire you if there is the possibility https://discord.gg/GBd8DcFsKf Can we talk privately in my community please? [Company@Galidar.online](mailto:Company@Galidar.online)

Verification~
